### PR TITLE
Ch06 Tweaks and Notes

### PR DESCRIPTION
**Pull request by jonthegeek**
Starting the PR so I can add comments as I find them. I was just jotting them down locally in notepad and had my first BSOD in years (they're green now!), so I figured I should do it online somewhere so notes autosave as I go...

### CODE REVIEW

**Comment by jonthegeek** [comment]
274: I swapped "S3" and "Simple Storage Service" to match the () format you mentioned, but you might want to add a footnote that S3 was an early service and the name actually makes sense, even if people usually just use the abbreviation.

429: What size/type should we choose? A simple idea here would help, along with info on when/where we'll learn more about EBS.

**Comment by akgold** [comment]
> 274: I swapped "S3" and "Simple Storage Service" to match the () format you mentioned, but you might want to add a footnote that S3 was an early service and the name actually makes sense, even if people usually just use the abbreviation.

I've been struggling with this question -- do you have any thoughts on whether I need to differentiate between things where they're basically always referred to by their acronym (e.g. S3) and the name is just trivia and where the name is more commonly used and I'm sharing the acronym for reference? I know standard practice is always to write out first and then put abbreviation in parens -- but curious if that's clear enough when the abbreviation is the common way to reference.

**Comment by jonthegeek** [comment]
I think it's fine to keep abbreviation first for all of them. O'Reilly might end up with thoughts around it, but I'd stick with it here with the explanation that the names are almost always meaningless.

**Comment by akgold** [comment]
Thanks for the edits, @jonthegeek! I didn't have a chance to incorporate till now, and I've rearranged, so I manually incorporated in #127.

**Pull request closed without merging**
