### PR TITLE
Update 1-1-code-promotion.qmd

### PR DESCRIPTION
**Pull request by jonthegeek**
Mostly typos, etc.

Some notes:

> I strongly recommend *The Phoenix Project* by Gene Kim, Kevin Behr, and George Spafford as a fun way to get acquainted if you're even remotely interested.

Interested in what, exactly? I'm interested in CI/CD; that's a big part of why I'm reading YOUR book. What more would I go to that particular book for?

(saving so I don't lose my changes that I'm making in the browser, but I'm not done reading the chapter yet).

### CODE REVIEW

**Comment by jonthegeek** [comment]
Two things that I find a little confusing in this:

1. I'm PRETTY sure you're differentiating between Dev, Test, and Prod *environments,* but the git branching strategy implies that they're 1:1 equivalent with *branches,* and I don't think they are.
2. Should you have an explicit test environment for this book? If not, do GHA checks "count" as a test environment in this case? That's how I usually think about it, but formally often you want an actual test deployment (depending on what the thing is). For example, I've had cases where I deploy to a test shinyapps URL for PR tests, then only deploy to prod when I merge into main. Generally... it seems like sometimes you don't REALLY have a full-fledged test environment, and it might be good to point out those lines.

Another push of typos coming and then I'll mark this ready for review.

**Comment by akgold** [comment]
Oh, realize I didn't answer 2. You're right that I don't -- maybe I should? I should think more about that. 

One reason it matters less in this case is that a failed deployment just means no update. Stakes are a lot lower than with an app, where deploying bad code means the app goes down.

**Comment by jonthegeek** [comment]
Yeah, but this *is* a form of production! We all have things like this where there isn't a formal dev environment, other than the temporary "environment" of a PR. Maybe explicitly discuss that, and when you'd consider it ok vs not ok?

**Comment by akgold** [comment]
Totally fair. 

I consider it reasonable when it's me and I'm being lazy and unreasonable if you're reading the book 😆 

But actually things have been so in flux that testing is the least of the issues with the book. As it gets closer to production, setting up a test env probably makes a lot of sense.

**Pull request merged**
